# ---------------------------------------------
# ⚠️ AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
# Source: backend/db/schemas/__init__.py, backend/db/data_models/__init__.py
# Generated by: backend/db/scripts/generate_sqlmodel_from_sql.py
# ---------------------------------------------

import enum
from datetime import datetime, timezone
from typing import Any, Optional, cast
from uuid import UUID, uuid4

from sqlalchemy.dialects.postgresql import JSON
from sqlmodel import Column, Enum, Field, SQLModel


def enum_values(enum_class: type[enum.Enum]) -> list[str]:
    """Get values for enum."""
    return [status.value for status in enum_class]


class ActorType(str, enum.Enum):
    USER = "user"
    JOB_MANAGER = "job_manager"
    JOB_PROCESSOR = "job_processor"
    WORKER_PROCESS = "worker_process"
    SYSTEM = "system"


class AssetUploadStatus(str, enum.Enum):
    PENDING = "pending"
    PROCESSING = "processing"
    READY = "ready"
    INVALID_MIME = "invalid_mime"
    PROCESSING_FAILED = "processing_failed"
    UPLOAD_FAILED = "upload_failed"
    UPLOAD_SUCCEEDED = "upload_succeeded"


class BackgroundType(str, enum.Enum):
    COLOR = "color"
    STATICIMG = "staticimg"


class CommentStatus(str, enum.Enum):
    VISIBLE = "visible"
    HIDDEN_BY_AUTHOR = "hidden_by_author"
    DELETED_BY_SYSTEM = "deleted_by_system"


class FontStyle(str, enum.Enum):
    UNSPECIFIED = "unspecified"


class IdentityKind(str, enum.Enum):
    GUEST = "guest"
    USER = "user"


class JobEventAction(str, enum.Enum):
    JOB_QUEUED = "job_queued"
    JOB_DEQUEUED = "job_dequeued"
    ATTEMPT_STARTED = "attempt_started"
    JOB_SUCCEEDED = "job_succeeded"
    ATTEMPT_FAILED = "attempt_failed"
    ATTEMPT_RETRY_SCHEDULED = "attempt_retry_scheduled"
    ATTEMPT_RETRY_EXHAUSTED = "attempt_retry_exhausted"
    JOB_MARKED_DEAD = "job_marked_dead"
    MANUAL_ATTEMPT_STARTED = "manual_attempt_started"
    JOB_ENQUEUE_FAILED = "job_enqueue_failed"
    LOG_INFO = "log_info"
    LOG_WARNING = "log_warning"
    LOG_EXCEPTION = "log_exception"


class JobStatus(str, enum.Enum):
    QUEUED = "queued"
    DEQUEUED = "dequeued"
    PROCESSING = "processing"
    DONE = "done"
    ERROR = "error"
    DEAD = "dead"
    ENQUEUE_FAILED = "enqueue_failed"


class NotificationDeliveryEvent(str, enum.Enum):
    PROCESSING = "processing"
    SENT = "sent"
    FAILED = "failed"


class NotificationStatus(str, enum.Enum):
    PENDING = "pending"
    SENT = "sent"
    FAILED = "failed"


class NotificationType(str, enum.Enum):
    COMMENT = "comment"
    SHARE = "share"
    MENTION = "mention"
    LIKE = "like"
    SYSTEM = "system"
    CUSTOM = "custom"


class OpenStyle(str, enum.Enum):
    TWOD_ENVELOPE = "twod_envelope"


class PageLayout(str, enum.Enum):
    DEFAULT = "default"
    POLAROID = "polaroid"
    MASONRY = "masonry"
    SURROUNDING = "surrounding"
    TWO_DIAGONAL = "two_diagonal"


class PhotobookStatus(str, enum.Enum):
    DRAFT = "draft"
    PENDING = "pending"
    DELETED = "deleted"
    PERMANENTLY_DELETED = "permanently_deleted"
    SHARED = "shared"


class PhotobookStatusEditor(str, enum.Enum):
    USER = "user"
    UPLOAD_PIPELINE = "upload_pipeline"
    GENERATION_PIPELINE = "generation_pipeline"
    SYSTEM = "system"


class ShareAccessPolicy(str, enum.Enum):
    ANYONE_WITH_LINK = "anyone_with_link"
    RECIPIENT_MUST_AUTH = "recipient_must_auth"
    REVOKED = "revoked"


class ShareChannelStatus(str, enum.Enum):
    PENDING = "pending"
    SCHEDULED = "scheduled"
    SENDING = "sending"
    SENT = "sent"
    FAILED = "failed"
    CANCELED = "canceled"


class ShareChannelType(str, enum.Enum):
    EMAIL = "email"
    SMS = "sms"
    APNS = "apns"


class ShareKind(str, enum.Enum):
    PUBLIC = "public"
    RECIPIENT = "recipient"


class ShareNotificationType(str, enum.Enum):
    SHARED_WITH_YOU = "shared_with_you"


class ShareProvider(str, enum.Enum):
    RESEND = "resend"
    TWILIO = "twilio"
    APNS = "apns"


class ShareRole(str, enum.Enum):
    VIEWER = "viewer"
    EDITOR = "editor"
    OWNER = "owner"


class UserProvidedOccasion(str, enum.Enum):
    WEDDING = "wedding"
    BIRTHDAY = "birthday"
    ANNIVERSARY = "anniversary"
    OTHER = "other"
    GIFT = "gift"
    MEMORY = "memory"
    TRIP = "trip"


class DAOAssets(SQLModel, table=True):
    __tablename__ = cast("Any", "assets")
    id: UUID = Field(primary_key=True, default_factory=uuid4, nullable=False)
    asset_key_original: Optional[str] = Field(default=None, nullable=True)
    asset_key_display: Optional[str] = Field(default=None, nullable=True)
    asset_key_llm: Optional[str] = Field(default=None, nullable=True)
    metadata_json: Optional[dict[str, Any]] = Field(
        default=None, nullable=True, sa_type=JSON
    )
    created_at: Optional[datetime] = Field(
        default_factory=lambda: datetime.now(timezone.utc), nullable=True
    )
    original_photobook_id: Optional[UUID] = Field(default=None, nullable=True)
    upload_status: AssetUploadStatus = Field(
        sa_column=Column(
            Enum(
                AssetUploadStatus,
                name="asset_upload_status",
                native_enum=True,
                nullable=False,
                values_callable=enum_values,
            )
        )
    )
    original_filename: Optional[str] = Field(default=None, nullable=True)
    exif: Optional[dict[str, Any]] = Field(default=None, nullable=True, sa_type=JSON)
    blur_data_url: Optional[str] = Field(default=None, nullable=True)
    asset_key_thumbnail: Optional[str] = Field(default=None, nullable=True)
    user_id: UUID = Field(nullable=False)


class DAOJobEvents(SQLModel, table=True):
    __tablename__ = cast("Any", "job_events")
    id: UUID = Field(primary_key=True, default_factory=uuid4, nullable=False)
    job_id: UUID = Field(nullable=False)
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc), nullable=False
    )
    event_action: JobEventAction = Field(
        sa_column=Column(
            Enum(
                JobEventAction,
                name="job_event_action",
                native_enum=True,
                nullable=False,
                values_callable=enum_values,
            )
        )
    )
    message: Optional[str] = Field(default=None, nullable=True)
    host: Optional[str] = Field(default=None, nullable=True)
    retry_count: Optional[int] = Field(default=0, nullable=True)
    extra: Optional[dict[str, Any]] = Field(default=None, nullable=True, sa_type=JSON)
    actor_type: ActorType = Field(
        sa_column=Column(
            Enum(
                ActorType,
                name="actor_type",
                native_enum=True,
                nullable=False,
                values_callable=enum_values,
            )
        )
    )
    actor_id: Optional[str] = Field(default=None, nullable=True)
    job_type: Optional[str] = Field(default=None, nullable=True)
    photobook_id: Optional[UUID] = Field(default=None, nullable=True)


class DAOJobs(SQLModel, table=True):
    __tablename__ = cast("Any", "jobs")
    id: UUID = Field(primary_key=True, default_factory=uuid4, nullable=False)
    job_type: str = Field(nullable=False)
    status: JobStatus = Field(
        sa_column=Column(
            Enum(
                JobStatus,
                name="job_status",
                native_enum=True,
                nullable=False,
                values_callable=enum_values,
            )
        )
    )
    input_payload: Optional[dict[str, Any]] = Field(
        default=None, nullable=True, sa_type=JSON
    )
    result_payload: Optional[dict[str, Any]] = Field(
        default=None, nullable=True, sa_type=JSON
    )
    error_message: Optional[str] = Field(default=None, nullable=True)
    user_id: Optional[UUID] = Field(default=None, nullable=True)
    photobook_id: Optional[UUID] = Field(default=None, nullable=True)
    created_at: Optional[datetime] = Field(
        default_factory=lambda: datetime.now(timezone.utc), nullable=True
    )
    started_at: Optional[datetime] = Field(default=None, nullable=True)
    completed_at: Optional[datetime] = Field(default=None, nullable=True)
    retry_count: Optional[int] = Field(default=0, nullable=True)
    max_retries: Optional[int] = Field(default=3, nullable=True)
    last_attempted_at: Optional[datetime] = Field(default=None, nullable=True)


class DAONotificationDeliveryAttempts(SQLModel, table=True):
    __tablename__ = cast("Any", "notification_delivery_attempts")
    id: UUID = Field(primary_key=True, default_factory=uuid4, nullable=False)
    share_channel_id: UUID = Field(nullable=False)
    notification_type: Optional[ShareNotificationType] = Field(
        default=None,
        sa_column=Column(
            Enum(
                ShareNotificationType,
                name="share_notification_type",
                native_enum=True,
                nullable=True,
                values_callable=enum_values,
            )
        ),
    )
    channel_type: ShareChannelType = Field(
        sa_column=Column(
            Enum(
                ShareChannelType,
                name="share_channel_type",
                native_enum=True,
                nullable=False,
                values_callable=enum_values,
            )
        )
    )
    provider: Optional[ShareProvider] = Field(
        default=None,
        sa_column=Column(
            Enum(
                ShareProvider,
                name="share_provider",
                native_enum=True,
                nullable=True,
                values_callable=enum_values,
            )
        ),
    )
    event: NotificationDeliveryEvent = Field(
        sa_column=Column(
            Enum(
                NotificationDeliveryEvent,
                name="notification_delivery_event",
                native_enum=True,
                nullable=False,
                values_callable=enum_values,
            )
        )
    )
    payload: Optional[dict[str, Any]] = Field(default=None, nullable=True, sa_type=JSON)
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc), nullable=False
    )
    notification_outbox_id: Optional[UUID] = Field(default=None, nullable=True)


class DAONotificationOutbox(SQLModel, table=True):
    __tablename__ = cast("Any", "notification_outbox")
    id: UUID = Field(primary_key=True, default_factory=uuid4, nullable=False)
    photobook_id: UUID = Field(nullable=False)
    share_id: UUID = Field(nullable=False)
    share_channel_id: UUID = Field(nullable=False)
    channel_type: ShareChannelType = Field(
        sa_column=Column(
            Enum(
                ShareChannelType,
                name="share_channel_type",
                native_enum=True,
                nullable=False,
                values_callable=enum_values,
            )
        )
    )
    provider: Optional[ShareProvider] = Field(
        default=None,
        sa_column=Column(
            Enum(
                ShareProvider,
                name="share_provider",
                native_enum=True,
                nullable=True,
                values_callable=enum_values,
            )
        ),
    )
    status: ShareChannelStatus = Field(
        sa_column=Column(
            Enum(
                ShareChannelStatus,
                name="share_channel_status",
                native_enum=True,
                nullable=False,
                values_callable=enum_values,
            )
        )
    )
    scheduled_for: Optional[datetime] = Field(default=None, nullable=True)
    last_error: Optional[str] = Field(default=None, nullable=True)
    last_provider_message_id: Optional[str] = Field(default=None, nullable=True)
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc), nullable=False
    )
    updated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc), nullable=False
    )
    notification_type: ShareNotificationType = Field(
        sa_column=Column(
            Enum(
                ShareNotificationType,
                name="share_notification_type",
                native_enum=True,
                nullable=False,
                values_callable=enum_values,
            )
        )
    )
    dispatch_token: Optional[UUID] = Field(default=None, nullable=True)
    created_by_user_id: UUID = Field(nullable=False)
    dispatch_claimed_at: Optional[datetime] = Field(default=None, nullable=True)
    idempotency_key: Optional[str] = Field(default=None, nullable=True)
    dispatch_lease_expires_at: Optional[datetime] = Field(default=None, nullable=True)
    dispatch_worker_id: Optional[str] = Field(default=None, nullable=True)
    canceled_at: Optional[datetime] = Field(default=None, nullable=True)
    canceled_by_user_id: Optional[UUID] = Field(default=None, nullable=True)
    scheduled_by_user_id: Optional[UUID] = Field(default=None, nullable=True)
    last_scheduled_at: Optional[datetime] = Field(default=None, nullable=True)


class DAONotifications(SQLModel, table=True):
    __tablename__ = cast("Any", "notifications")
    id: UUID = Field(primary_key=True, default_factory=uuid4, nullable=False)
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc), nullable=False
    )
    recipient_id: UUID = Field(nullable=False)
    actor_id: Optional[UUID] = Field(default=None, nullable=True)
    type: NotificationType = Field(
        sa_column=Column(
            Enum(
                NotificationType,
                name="notification_type",
                native_enum=True,
                nullable=False,
                values_callable=enum_values,
            )
        )
    )
    photobook_id: Optional[UUID] = Field(default=None, nullable=True)
    comment_id: Optional[UUID] = Field(default=None, nullable=True)
    share_id: Optional[UUID] = Field(default=None, nullable=True)
    title: Optional[str] = Field(default=None, nullable=True)
    body: Optional[str] = Field(default=None, nullable=True)
    cta_url: Optional[str] = Field(default=None, nullable=True)
    payload: dict[str, Any] = Field(default="{}'::jsonb", nullable=False, sa_type=JSON)
    group_key: Optional[str] = Field(default=None, nullable=True)
    seen_at: Optional[datetime] = Field(default=None, nullable=True)


class DAOPages(SQLModel, table=True):
    __tablename__ = cast("Any", "pages")
    id: UUID = Field(primary_key=True, default_factory=uuid4, nullable=False)
    photobook_id: Optional[UUID] = Field(default=None, nullable=True)
    page_number: int = Field(nullable=False)
    user_message: Optional[str] = Field(default=None, nullable=True)
    layout: Optional[PageLayout] = Field(
        default=None,
        sa_column=Column(
            Enum(
                PageLayout,
                name="page_layout",
                native_enum=True,
                nullable=True,
                values_callable=enum_values,
            )
        ),
    )
    created_at: Optional[datetime] = Field(
        default_factory=lambda: datetime.now(timezone.utc), nullable=True
    )
    user_message_alternative_options: Optional[dict[str, Any]] = Field(
        default=None, nullable=True, sa_type=JSON
    )
    revision: int = Field(default=1, nullable=False)
    user_message_alternative_options_outdated: bool = Field(
        default=False, nullable=False
    )
    page_lightweight_title: Optional[str] = Field(default=None, nullable=True)


class DAOPagesAssetsRel(SQLModel, table=True):
    __tablename__ = cast("Any", "pages_assets_rel")
    id: UUID = Field(primary_key=True, default_factory=uuid4, nullable=False)
    page_id: Optional[UUID] = Field(default=None, nullable=True)
    asset_id: Optional[UUID] = Field(default=None, nullable=True)
    order_index: Optional[int] = Field(default=None, nullable=True)
    caption: Optional[str] = Field(default=None, nullable=True)


class DAOPhotobookBookmarks(SQLModel, table=True):
    __tablename__ = cast("Any", "photobook_bookmarks")
    id: UUID = Field(primary_key=True, default_factory=uuid4, nullable=False)
    user_id: UUID = Field(nullable=False)
    photobook_id: UUID = Field(nullable=False)
    created_at: Optional[datetime] = Field(
        default_factory=lambda: datetime.now(timezone.utc), nullable=True
    )
    source: Optional[str] = Field(default=None, nullable=True)


class DAOPhotobookComments(SQLModel, table=True):
    __tablename__ = cast("Any", "photobook_comments")
    id: UUID = Field(primary_key=True, default_factory=uuid4, nullable=False)
    photobook_id: UUID = Field(nullable=False)
    user_id: Optional[UUID] = Field(default=None, nullable=True)
    guest_name: Optional[str] = Field(default=None, nullable=True)
    guest_email: Optional[str] = Field(default=None, nullable=True)
    body: str = Field(nullable=False)
    status: CommentStatus = Field(
        sa_column=Column(
            Enum(
                CommentStatus,
                name="comment_status",
                native_enum=True,
                nullable=False,
                values_callable=enum_values,
            )
        )
    )
    notification_status: NotificationStatus = Field(
        sa_column=Column(
            Enum(
                NotificationStatus,
                name="notification_status",
                native_enum=True,
                nullable=False,
                values_callable=enum_values,
            )
        )
    )
    commenter_ip: Optional[str] = Field(default=None, nullable=True)
    user_agent: Optional[str] = Field(default=None, nullable=True)
    created_at: Optional[datetime] = Field(
        default_factory=lambda: datetime.now(timezone.utc), nullable=True
    )
    updated_at: Optional[datetime] = Field(
        default_factory=lambda: datetime.now(timezone.utc), nullable=True
    )
    last_updated_by: Optional[UUID] = Field(default=None, nullable=True)


class DAOPhotobookSettings(SQLModel, table=True):
    __tablename__ = cast("Any", "photobook_settings")
    id: UUID = Field(primary_key=True, default_factory=uuid4, nullable=False)
    photobook_id: UUID = Field(nullable=False)
    main_style: Optional[str] = Field(default=None, nullable=True)
    font: FontStyle = Field(
        sa_column=Column(
            Enum(
                FontStyle,
                name="font_style",
                native_enum=True,
                nullable=False,
                values_callable=enum_values,
            )
        )
    )
    is_comment_enabled: bool = Field(default=False, nullable=False)
    is_allow_download_all_images_enabled: bool = Field(default=False, nullable=False)
    is_tipping_enabled: bool = Field(default=False, nullable=False)
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc), nullable=False
    )
    updated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc), nullable=False
    )


class DAOPhotobookShare(SQLModel, table=True):
    __tablename__ = cast("Any", "photobook_share")
    id: UUID = Field(primary_key=True, default_factory=uuid4, nullable=False)
    photobook_id: UUID = Field(nullable=False)
    email: Optional[str] = Field(default=None, nullable=True)
    invited_user_id: Optional[UUID] = Field(default=None, nullable=True)
    role: ShareRole = Field(
        sa_column=Column(
            Enum(
                ShareRole,
                name="share_role",
                native_enum=True,
                nullable=False,
                values_callable=enum_values,
            )
        )
    )
    email_notification_status: Optional[NotificationStatus] = Field(
        sa_column=Column(
            Enum(
                NotificationStatus,
                name="notification_status",
                native_enum=True,
                nullable=True,
                values_callable=enum_values,
            )
        )
    )
    custom_message: Optional[str] = Field(default=None, nullable=True)
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc), nullable=False
    )
    updated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc), nullable=False
    )


class DAOPhotobooks(SQLModel, table=True):
    __tablename__ = cast("Any", "photobooks")
    id: UUID = Field(primary_key=True, default_factory=uuid4, nullable=False)
    title: str = Field(nullable=False)
    caption: Optional[str] = Field(default=None, nullable=True)
    theme: Optional[str] = Field(default=None, nullable=True)
    status: Optional[PhotobookStatus] = Field(
        default=None,
        sa_column=Column(
            Enum(
                PhotobookStatus,
                name="photobook_status",
                native_enum=True,
                nullable=True,
                values_callable=enum_values,
            )
        ),
    )
    created_at: Optional[datetime] = Field(
        default_factory=lambda: datetime.now(timezone.utc), nullable=True
    )
    updated_at: Optional[datetime] = Field(
        default_factory=lambda: datetime.now(timezone.utc), nullable=True
    )
    user_provided_occasion: Optional[UserProvidedOccasion] = Field(
        default=None,
        sa_column=Column(
            Enum(
                UserProvidedOccasion,
                name="user_provided_occasion",
                native_enum=True,
                nullable=True,
                values_callable=enum_values,
            )
        ),
    )
    user_provided_occasion_custom_details: Optional[str] = Field(
        default=None, nullable=True
    )
    user_provided_context: Optional[str] = Field(default=None, nullable=True)
    thumbnail_asset_id: Optional[UUID] = Field(default=None, nullable=True)
    deleted_at: Optional[datetime] = Field(default=None, nullable=True)
    status_last_edited_by: Optional[PhotobookStatusEditor] = Field(
        sa_column=Column(
            Enum(
                PhotobookStatusEditor,
                name="photobook_status_editor",
                native_enum=True,
                nullable=True,
                values_callable=enum_values,
            )
        )
    )
    background_color_palette: Optional[str] = Field(default=None, nullable=True)
    user_gift_recipient: Optional[str] = Field(default=None, nullable=True)
    suggested_overall_gift_message: Optional[str] = Field(default=None, nullable=True)
    suggested_overall_gift_message_tone: Optional[str] = Field(
        default=None, nullable=True
    )
    suggested_overall_gift_message_alternative_options: Optional[dict[str, Any]] = (
        Field(default=None, nullable=True, sa_type=JSON)
    )
    user_id: UUID = Field(nullable=False)
    background: BackgroundType = Field(
        sa_column=Column(
            Enum(
                BackgroundType,
                name="background_type",
                native_enum=True,
                nullable=False,
                values_callable=enum_values,
            )
        )
    )
    bg_img_name: Optional[str] = Field(default=None, nullable=True)
    open_style: Optional[OpenStyle] = Field(
        default=None,
        sa_column=Column(
            Enum(
                OpenStyle,
                name="open_style",
                native_enum=True,
                nullable=True,
                values_callable=enum_values,
            )
        ),
    )
    open_param: Optional[dict[str, Any]] = Field(
        default=None, nullable=True, sa_type=JSON
    )


class DAOPhotobooksAssetsRel(SQLModel, table=True):
    __tablename__ = cast("Any", "photobooks_assets_rel")
    id: UUID = Field(primary_key=True, default_factory=uuid4, nullable=False)
    photobook_id: UUID = Field(nullable=False)
    asset_id: UUID = Field(nullable=False)


class DAOShareChannels(SQLModel, table=True):
    __tablename__ = cast("Any", "share_channels")
    id: UUID = Field(primary_key=True, default_factory=uuid4, nullable=False)
    photobook_share_id: UUID = Field(nullable=False)
    photobook_id: UUID = Field(nullable=False)
    channel_type: ShareChannelType = Field(
        sa_column=Column(
            Enum(
                ShareChannelType,
                name="share_channel_type",
                native_enum=True,
                nullable=False,
                values_callable=enum_values,
            )
        )
    )
    destination: str = Field(nullable=False)
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc), nullable=False
    )
    updated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc), nullable=False
    )


class DAOShares(SQLModel, table=True):
    __tablename__ = cast("Any", "shares")
    id: UUID = Field(primary_key=True, default_factory=uuid4, nullable=False)
    photobook_id: UUID = Field(nullable=False)
    created_by_user_id: Optional[UUID] = Field(default=None, nullable=True)
    kind: ShareKind = Field(
        sa_column=Column(
            Enum(
                ShareKind,
                name="share_kind",
                native_enum=True,
                nullable=False,
                values_callable=enum_values,
            )
        )
    )
    sender_display_name: Optional[str] = Field(default=None, nullable=True)
    recipient_display_name: Optional[str] = Field(default=None, nullable=True)
    recipient_user_id: Optional[UUID] = Field(default=None, nullable=True)
    share_slug: str = Field(nullable=False)
    access_policy: ShareAccessPolicy = Field(
        sa_column=Column(
            Enum(
                ShareAccessPolicy,
                name="share_access_policy",
                native_enum=True,
                nullable=False,
                values_callable=enum_values,
            )
        )
    )
    notes: Optional[str] = Field(default=None, nullable=True)
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc), nullable=False
    )
    updated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc), nullable=False
    )
    revoked_at: Optional[datetime] = Field(default=None, nullable=True)
    revoked_by_user_id: Optional[UUID] = Field(default=None, nullable=True)
    revoked_reason: Optional[str] = Field(default=None, nullable=True)


class DAOUserRecentlyViewedPhotobook(SQLModel, table=True):
    __tablename__ = cast("Any", "user_recently_viewed_photobook")
    user_id: UUID = Field(primary_key=True, nullable=False)
    photobook_id: UUID = Field(primary_key=True, nullable=False)
    viewed_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc), nullable=False
    )


class DAOUsers(SQLModel, table=True):
    __tablename__ = cast("Any", "users")
    id: UUID = Field(primary_key=True, nullable=False)
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc), nullable=False
    )
    email: Optional[str] = Field(default=None, nullable=True)
    phone: Optional[str] = Field(default=None, nullable=True)
    email_confirmed_at: Optional[datetime] = Field(default=None, nullable=True)
    phone_confirmed_at: Optional[datetime] = Field(default=None, nullable=True)
    name: Optional[str] = Field(default=None, nullable=True)
    role: str = Field(default="user'::text", nullable=False)
    bmc_link: Optional[str] = Field(default=None, nullable=True)
